name: Validate lavamoat policy build

on:
  workflow_call:

jobs:
  validate-lavamoat-policy-build:
    name: Validate lavamoat policy build
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment
        uses: metamask/github-tools/.github/actions/setup-environment@caching
        with:
          should-cache-restore: ${{ vars.USE_CACHING }}

      - name: Validate lavamoat build policy
        run: yarn lavamoat:build:auto
        env:
          INFURA_PROJECT_ID: 00000000000

      - name: Check working tree
        run: |
          if ! git diff --exit-code; then
              echo "::error::Working tree dirty."
              exit 1
          fi
